### ISSUE TITLE
Plugin InteractionVisualizer v1.0.0 generated an exception while executing task 11256424

### ISSUE THREAD

**Issue by Ghost-chu** [LOOHP/InteractionVisualizer#1]
[22:23:20 WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.0.0 generated an exception while executing task 11256424
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_241]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_241]
at com.loohp.interactionvisualizer.Utils.PacketSending.removeItem(PacketSending.java:294) ~[?:?]
at com.loohp.interactionvisualizer.Utils.PacketSending.removeItem(PacketSending.java:303) ~[?:?]
at com.loohp.interactionvisualizer.Blocks.DoubleChestDisplay$1.run(DoubleChestDisplay.java:160) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[PaperSpigot-1.15.2.jar:git-Paper-158]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[PaperSpigot-1.15.2.jar:git-Paper-158]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[PaperSpigot-1.15.2.jar:git-Paper-158]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

**Comment by LOOHP** [comment]
I'm trying to replicate the error but I can't seem to do it. Can you elaborate on what were you doing when the error pops up? Thanks :)

**Comment by Ghost-chu** [comment]
just install and boom.
it seems is a thread safe issue, you might need have 2 and more players to test in&nbsp; same time




packet is sync, you must keep thread safe



---Original---

**Comment by LOOHP** [comment]
Yea, I've changed the ArrayList involved into a CopyOnWriteArrayList and it seemed to have worked for now.
