### ISSUE TITLE
Unable to download latest languages files from Mojang

### ISSUE THREAD

**Issue by cupang-afk** [LOOHP/InteractionVisualizer#100]
```
[22:12:03 INFO]: [InteractionVisualizer] Unable to download latest languages files from Mojang
[22:12:03 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[22:12:03 WARN]: 	at java.base/java.io.StringReader.<init>(StringReader.java:51)
[22:12:03 WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:79)
[22:12:03 WARN]: 	at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[22:12:03 WARN]: 	at InteractionVisualizer-LATEST-[97].jar//com.loohp.interactionvisualizer.utils.HTTPRequestUtils.getJSONResponse(HTTPRequestUtils.java:45)
[22:12:03 WARN]: 	at InteractionVisualizer-LATEST-[97].jar//com.loohp.interactionvisualizer.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:116)
[22:12:03 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[22:12:03 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:12:03 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:12:03 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:12:03 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:12:03 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
if the "Mojang" url is https://piston-meta.mojang.com/

its accessible from my network using `ping`
```bash
➜  ~ ping piston-meta.mojang.com
PING part-0031.t-0009.fdv2-t-msedge.net (13.107.237.59) 56(84) bytes of data.
64 bytes from 13.107.237.59 (13.107.237.59): icmp_seq=1 ttl=54 time=17.0 ms
64 bytes from 13.107.237.59 (13.107.237.59): icmp_seq=2 ttl=54 time=16.7 ms
64 bytes from 13.107.237.59 (13.107.237.59): icmp_seq=3 ttl=54 time=16.8 ms
64 bytes from 13.107.237.59 (13.107.237.59): icmp_seq=4 ttl=54 time=17.8 ms
```
also still accessible when downloading 1.19.4.json using `curl`
```bash
➜  ~ curl -OL https://piston-meta.mojang.com/v1/packages/01a4c81e3a15f5f946ac9c2750fe4dc6a93bc5bc/1.19.4.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34407  100 34407    0     0  69115      0 --:--:-- --:--:-- --:--:-- 69090
```

---
plugin version
```
[22:11:26 INFO]: [InteractionVisualizer] Loading server plugin InteractionVisualizer v1.18.4.0
```

server version
```
[22:13:22 INFO]: Current: git-Purpur-1967 (MC: 1.19.4)*
Previous: git-Paper-524 (MC: 1.19.4)
* You are running the latest version
```

**Comment by LOOHP** [comment]
Sometimes there might be drop outs in the network, if the plugin continues to work fine, it's alright.

**Comment by cupang-afk** [comment]
> Sometimes there might be drop outs in the network, if the plugin continues to work fine, it's alright.

_(so fast reply)_

well the plugin is working fine because it already downloaded the language files before

but im afraid if i somehow accidentaly deleted the language files, and this error happen
does it affect the plugin ?

also i opened the similar issue with your another plugin at https://github.com/LOOHP/InteractiveChat/issues/145
if your answer  for above question applied for both plugin, then i'll close them

**Comment by LOOHP** [comment]
It should be fine, it's probably just a connection issue at that moment.

**Comment by cupang-afk** [comment]
okay thank you for your time
