### ISSUE TITLE
[InteractionVisualizer] Unable to download latest languages files from Mojang

### ISSUE THREAD

**Issue by TheFaik** [LOOHP/InteractionVisualizer#101]
```
[23:15:11 INFO]: [InteractionVisualizer] Unable to download latest languages files from Mojang
[23:15:11 WARN]: java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
[23:15:11 WARN]:        at java.base/java.io.StringReader.<init>(StringReader.java:51)
[23:15:11 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:79)
[23:15:11 WARN]:        at org.json.simple.parser.JSONParser.parse(JSONParser.java:75)
[23:15:11 WARN]:        at InteractionVisualizer-1.18.4.0.jar//com.loohp.interactionvisualizer.utils.HTTPRequestUtils.getJSONResponse(HTTPRequestUtils.java:45)
[23:15:11 WARN]:        at InteractionVisualizer-1.18.4.0.jar//com.loohp.interactionvisualizer.utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:116)
[23:15:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:15:11 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:15:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:15:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:15:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:15:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by LOOHP** [comment]
Most likely just a one time connection issue, if it doesn't happen every time you restart.
