### ISSUE TITLE
Version 1.18.8 Not Working in Paper 1.12.2

### ISSUE THREAD

**Issue by MelodyYuuka** [LOOHP/InteractionVisualizer#115]
The server logs are as follows
```
Error occurred while enabling InteractionVisualizer v1.18.8.0 (Is it up to date?)
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
        at com.loohp.interactionvisualizer.entities.ItemDisplay.lambda$onReload$5(ItemDisplay.java:119) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558) ~[?:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay.onReload(ItemDisplay.java:136) ~[?:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay.<init>(ItemDisplay.java:103) ~[?:?]
        at com.loohp.interactionvisualizer.managers.TaskManager.setup(TaskManager.java:405) ~[?:?]
        at com.loohp.interactionvisualizer.InteractionVisualizer.onEnable(InteractionVisualizer.java:258) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]                                                                          at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]                                                                                at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]                                                                                at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]                                                                                at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]                                                                             at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]                                                                              at java.lang.Thread.run(Thread.java:829) [?:?]                                                                      
```

**Comment by MelodyYuuka** [comment]
After deleting the old configuration, it works properly. Sorry to disturb you

**Comment by LOOHP** [comment]
Try generating a new config and see if this error goes away.
