### ISSUE TITLE
Errors with MYSQL

### ISSUE THREAD

**Issue by Krissssik** [LOOHP/InteractionVisualizer#120]
[InteractionVisualizer] MYSQL Failed to connect! (SQLException)
[00:09:33 WARN]: java.sql.SQLNonTransientConnectionException: Too many connections
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[00:09:33 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[00:09:33 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.database.Database.mysqlSetup(Database.java:101)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.database.Database.open(Database.java:82)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.database.Database.getPlayerInfo(Database.java:382)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.managers.PreferenceManager.loadPlayer(PreferenceManager.java:169)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.managers.PreferenceManager.lambda$onJoinEvent$2(PreferenceManager.java:148)
[00:09:33 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:09:33 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:09:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:09:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:09:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[00:09:33 WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1648)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1564)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.database.Database.getPlayerInfo(Database.java:384)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.managers.PreferenceManager.loadPlayer(PreferenceManager.java:169)
[00:09:33 WARN]:        at InteractionVisualizer-1.18.10.0.jar//com.loohp.interactionvisualizer.managers.PreferenceManager.lambda$onJoinEvent$2(PreferenceManager.java:148)
[00:09:33 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:09:33 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:09:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:09:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:09:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[00:09:33 WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[00:09:33 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:09:33 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[00:09:33 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:09:33 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[00:09:33 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[00:09:33 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[00:09:33 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[00:09:33 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[00:09:33 WARN]:        at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:762)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
[00:09:33 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1579)
[00:09:33 WARN]:        ... 9 more

**Comment by LOOHP** [comment]
Try increasing the max connections count in your SQL server.

**Comment by Krissssik** [comment]
Excuse me, how and where?

**Comment by LOOHP** [comment]
You do it on your MYSQL server.
https://stackoverflow.com/questions/22297773/how-to-increase-mysql-connectionsmax-connections
