### ISSUE TITLE
[bug]Language file cannot be generated normally

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#16]
The new version of the plug-in (1.9.0) seems to be unable to generate language files normally. Although I tried to delete the entire file, it still does not generate.

**Comment by BackWheel** [comment]
`[21:09:03 WARN]: java.io.FileNotFoundException: plugins\%5B全息%5DInteractionVisualizer-1.9.0.jar (系统找不到指定的文件 。)
[21:09:03 WARN]:        at java.util.zip.ZipFile.open(Native Method)
[21:09:03 WARN]:        at java.util.zip.ZipFile.<init>(Unknown Source)
[21:09:03 WARN]:        at java.util.zip.ZipFile.<init>(Unknown Source)
[21:09:03 WARN]:        at java.util.jar.JarFile.<init>(Unknown Source)
[21:09:03 WARN]:        at java.util.jar.JarFile.<init>(Unknown Source)
[21:09:03 WARN]:        at com.loohp.interactionvisualizer.Manager.LangManager.generate(LangManager.java:32)
[21:09:03 WARN]:        at com.loohp.interactionvisualizer.InteractionVisualizer.onEnable(InteractionVisualizer.java:81)
[21:09:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:09:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
[21:09:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[21:09:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[21:09:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[21:09:03 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487)
[21:09:03 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[21:09:03 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:891)
[21:09:03 WARN]:        at java.lang.Thread.run(Unknown Source)`

I found related errors

**Comment by LOOHP** [comment]
Please give 1.9.2 a try and see if it works :)

**Comment by BackWheel** [comment]
Yes, it is work
