### ISSUE TITLE
[bug]Console warm

### ISSUE THREAD

**Issue by BackWheel** [LOOHP/InteractionVisualizer#24]
[19:29:41 WARN]: java.lang.NullPointerException
[19:29:41 WARN]:        at java.util.TreeMap.putAll(Unknown Source)
[19:29:41 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.save(CustomBlockDataManager.java:69)
[19:29:41 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager$1.run(CustomBlockDataManager.java:39)
[19:29:41 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[19:29:41 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:29:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:29:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:29:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:29:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:30:11 WARN]: java.lang.NullPointerException
[19:30:11 WARN]:        at java.util.TreeMap.putAll(Unknown Source)
[19:30:11 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.save(CustomBlockDataManager.java:69)
[19:30:11 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager$1.run(CustomBlockDataManager.java:39)
[19:30:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[19:30:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:30:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:30:11 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:30:11 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:30:11 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:30:41 WARN]: java.lang.NullPointerException
[19:30:41 WARN]:        at java.util.TreeMap.putAll(Unknown Source)
[19:30:41 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.save(CustomBlockDataManager.java:69)
[19:30:41 WARN]:        at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager$1.run(CustomBlockDataManager.java:39)
[19:30:41 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[19:30:41 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:30:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:30:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:30:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:30:41 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by LOOHP** [comment]
Can you send me your blockdata.json to take a look?
Is this spamming or just happens one of twice?

**Comment by BackWheel** [comment]
this is spamming

**Comment by BackWheel** [comment]
I tried to regenerate blockdata.json, it seems that there is no such problem.

**Comment by LOOHP** [comment]
Perhaps I'll add backups for blockdata.json incase anything happens.

**Comment by BackWheel** [comment]
thanks
