### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Volgeop** [LOOHP/InteractionVisualizer#28]
```
[00:56:10 WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.12.4 generated an exception while executing task 363641
java.lang.NullPointerException: null
at com.loohp.interactionvisualizer.Blocks.BrewingStandDisplay.lambda$5(BrewingStandDisplay.java:218) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-86]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-86]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]

```

**Comment by LOOHP** [comment]
Do you know when does this error occur?

**Comment by Volgeop** [comment]
Not sure :/  But it's something with brewingstand by log? Maybe something with brewery plugin too?

**Comment by LOOHP** [comment]
Well I tried using brewing stand and it worked fone

**Comment by LOOHP** [comment]
Merge with #30
