### ISSUE TITLE
Asynchronous Async Chunk Load

### ISSUE THREAD

**Issue by HiImSunny** [LOOHP/InteractionVisualizer#33]
[21:00:47 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[21:00:47 WARN]:        at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:00:47 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:170)
[21:00:47 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:153)
[21:00:47 WARN]:        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.getBlock(CraftBlockState.java:139)
[21:00:47 WARN]:        at com.loohp.interactionvisualizer.Managers.TileEntityManager.loadTileEntities(TileEntityManager.java:127)
[21:00:47 WARN]:        at com.loohp.interactionvisualizer.Managers.TileEntityManager.lambda$loadBlockStates$3(TileEntityManager.java:109)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[21:00:47 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[21:00:47 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:00:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:00:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:00:47 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by LOOHP** [comment]
Try setting `TileEntityUpdate.LoadTileEntitiesAsync` in the config to false.

**Comment by HiImSunny** [comment]
ok it work, tks
