### ISSUE TITLE
Warns spam

### ISSUE THREAD

**Issue by KupKa1221** [LOOHP/InteractionVisualizer#36]
[20:37:52 WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.13.6 generated an exception while executing task 48702091
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:80) ~[?:?]
        at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$11(PacketManager.java:275) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-162]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-162]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LOOHP** [comment]
Sorry for the late response, this is probably caused by not using the latest dev build for 1.16.3 of ProtocolLibrary

**Comment by LOOHP** [comment]
Closed due to inactivity.
