### ISSUE TITLE
Could not pass event InventoryClickEvent to InteractionVisualizer v1.13.9

### ISSUE THREAD

**Issue by Fargus5** [LOOHP/InteractionVisualizer#37]
Hello, I've found a error report in console

https://log.mtxserv.com/xBWSQnE

```

[10:32:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to InteractionVisualizer v1.13.9
--
2338 | java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
2339 | at java.util.Arrays$ArrayList.get(Arrays.java:4351) ~[?:?]
2340 | at net.minecraft.server.v1_16_R2.NonNullList.get(SourceFile:46) ~[patched_1.16.3.jar:git-Paper-246]
2341 | at net.minecraft.server.v1_16_R2.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.3.jar:git-Paper-246]
2342 | at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.3.jar:git-Paper-246]
2343 | at com.loohp.interactionvisualizer.Blocks.DoubleChestDisplay.onUseDoubleChest(DoubleChestDisplay.java:145) ~[?:?]
2344 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor904.execute(Unknown Source) ~[?:?]
2345 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-246]
2346 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-246]
2347 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-246]
2348 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-246]
2349 | at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2437) ~[patched_1.16.3.jar:git-Paper-246]
2350 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.3.jar:git-Paper-246]
2351 | at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-246]
2352 | at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-246]
2353 | at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-246]
2354 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-246]
2355 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-246]
2356 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-246]
2357 | at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-246]
2358 | at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-246]
2359 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-246]
2360 | at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-246]
2361 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-246]
2362 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
2363 | at java.lang.Thread.run(Thread.java:834) [?:?]


```

Could u check this and tell me what is the problem.?

**Comment by LOOHP** [comment]
This is very weird and is probably some edge case.
Basically, the server believes that a hotbar button is used to move items in an inventory yet the hotbar button is -1.
I will try to fix that in the next update.
For the meantime, it should be fine to ignore if the plugin continues to work after it.

**Comment by Fargus5** [comment]
Ok thanks u very mutch

**Comment by LOOHP** [comment]
Should be fixed in the latest build.

**Comment by Fargus5** [comment]
Downloaded 👍 
Thanks a lot
