### ISSUE TITLE
Warn spam when staring server

### ISSUE THREAD

**Issue by bungeeaumond** [LOOHP/InteractionVisualizer#38]
So this pops up everytime i start my server. Ive checked protocolib and its on 4.5.1 and lightapi is on its latest version. 
Unexpected token END OF FILE at position 4096.
at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.setup(CustomBlockDataManager.java:85)
at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.save(CustomBlockDataManager.java:114)
at com.loohp.interactionvisualizer.Managers.CustomBlockDataManager.lambda$intervalSaveToFile$0(CustomBlockDataManager.java:45)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by LOOHP** [comment]
Try replacing the blockdata.json in the plugin folder with one of the backups in the backup folder also in the plugin folder

**Comment by LOOHP** [comment]
Closed due to inactivity.
