### ISSUE TITLE
NoClassDefFoundError - LightApi related

### ISSUE THREAD

**Issue by TUCAOEVER** [LOOHP/InteractionVisualizer#39]
```
[08:07:36 WARN]: [InteractionVisualizer] Task #21445959 for InteractionVisualizer v1.13.9 generated an exception
java.lang.NoClassDefFoundError: ru/beykerykt/lightapi/LightType
        at com.loohp.interactionvisualizer.Managers.LightManager.deleteLight(LightManager.java:88) ~[?:?]
        at com.loohp.interactionvisualizer.Blocks.CraftingTableDisplay.process(CraftingTableDisplay.java:270) ~[?:?]
        at com.loohp.interactionvisualizer.Managers.TaskManager.lambda$run$0(TaskManager.java:300) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261]
        at com.loohp.interactionvisualizer.Managers.TaskManager.lambda$run$1(TaskManager.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-389]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265) ~[patched_1.15.2.jar:git-Paper-389]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-389]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-389]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-389]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Comment by TUCAOEVER** [comment]
> Are you running the latest version of LightAPI?
> (As of now: https://github.com/Qveshn/LightAPI/releases/tag/3.4.5)

Sure.I am using 3.4.5 version of LightAPI on my server.

**Comment by LOOHP** [comment]
So did it work using the version of LightAPI ?

**Comment by TUCAOEVER** [comment]
> So did it work using the version of LightAPI ?

Alright.I found that latest version of LightAPI dosen't load correctly on 1.15.2 server, so it's might wrong with LightAPI itself.

**Comment by LOOHP** [comment]
Are you running the latest version of LightAPI?
(As of now: https://github.com/Qveshn/LightAPI/releases/tag/3.4.5)

**Comment by LOOHP** [comment]
Closed due to inactivity.
