### ISSUE TITLE
Error since new ver and 3 lang folders?

### ISSUE THREAD

**Issue by bobhenl** [LOOHP/InteractionVisualizer#47]
```
[04:03:13] [Craft Scheduler Thread - 47 - InteractionVisualizer/WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.14.4.0 generated an exception while executing task 3931
java.lang.NoSuchMethodError: java.io.FileReader.<init>(Ljava/io/File;Ljava/nio/charset/Charset;)V
	at com.loohp.interactionvisualizer.Utils.LanguageUtils.lambda$loadTranslations$3(LanguageUtils.java:149) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Yatopia-7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Yatopia-7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by LOOHP** [comment]
Should be fixed in the latest dev build.
