### ISSUE TITLE
Animations don't work

### ISSUE THREAD

**Issue by DamirLut** [LOOHP/InteractionVisualizer#49]
An error appears in the console:
[InteractionVisualizer] Plugin InteractionVisualizer v1.14.4.1 generated an exception while executing task 4482
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:77) ~[?:?]
at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$4(PacketManager.java:215) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-332]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-332]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-332]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

How can this be solved? Installed all dependencies.

**Comment by LOOHP** [comment]
You need to use the latest dev build of protocollib

**Comment by DamirLut** [comment]
I am using 4.2.1 version of protocollib

**Comment by LOOHP** [comment]
The latest dev build is 4.6.0-SNAPSHOT

**Comment by DamirLut** [comment]
It helped! But there was a new error:
[InteractionVisualizer] Plugin InteractionVisualizer v1.14.4.1 generated an exception while executing task 2424
java.lang.NullPointerException: null
at java.lang.Enum.valueOf(Enum.java:232) ~[?:1.8.0_275]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:802) ~[?:?]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getGeneric(EnumWrappers.java:786) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:328) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters$3.getGeneric(BukkitConverters.java:325) ~[?:?]
at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:47) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters$2.getGeneric(BukkitConverters.java:301) ~[?:?]
at com.comphenix.protocol.wrappers.BukkitConverters$2.getGeneric(BukkitConverters.java:268) ~[?:?]
at com.comphenix.protocol.wrappers.Converters$1.getGeneric(Converters.java:47) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:372) ~[?:?]
at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:79) ~[?:?]
at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$4(PacketManager.java:215) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-332]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-332]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-332]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by LOOHP** [comment]
Make sure you are using the latest build of Paper for your choice of version and the latest build of 4.6.0-SNAPSHOT protcollib.
If despite the error, the plugin works fine. It can be safely ignored.
