### ISSUE TITLE
Error submission

### ISSUE THREAD

**Issue by StarYunmeng** [LOOHP/InteractionVisualizer#52]
[17:53:26 WARN]: [InteractionVisualizer] Plugin InteractionVisualizer v1.14.4.3 generated an exception while executing task 195197
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at com.loohp.interactionvisualizer.Protocol.ServerPacketSender.spawnArmorStand(ServerPacketSender.java:77) ~[?:?]
        at com.loohp.interactionvisualizer.Managers.PacketManager.lambda$sendArmorStandSpawn$4(PacketManager.java:214) ~[?:?]
        at com.loohp.interactionvisualizer.Managers.PacketManager$$Lambda$7960/0000000000000000.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-416]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-416]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-416]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:821) [?:1.8.0_242]

**Comment by LOOHP** [comment]
Try updating protocollib to the latest dev version.
