### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by Stonewall0210** [LOOHP/InteractionVisualizer#56]
```
[20:40:03 ERROR]: Error occurred while enabling InteractionVisualizer v1.14.10.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.bukkit.configuration.file.FileConfiguration.getList(String)" is null
        at com.loohp.interactionvisualizer.entities.ItemDisplay.onReload(ItemDisplay.java:76) ~[?:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay.<init>(ItemDisplay.java:63) ~[?:?]
        at com.loohp.interactionvisualizer.managers.TaskManager.setup(TaskManager.java:357) ~[?:?]
        at com.loohp.interactionvisualizer.InteractionVisualizer.onEnable(InteractionVisualizer.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-677]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-677]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-677]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-677]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-677]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-677]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-677]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-677]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-677]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```
I updated to fix console spam, and keep having this error. I didn't do much troubleshooting but I'm tired and wanted to see if this was a known bug before I make the stupid decision of trying to fix it myself
I can provide more info if needed

**Comment by Stonewall0210** [comment]
Oops, disregard this. I fixed it
Didn't realise that the browser was holding up giving me the actual download for the new version. Sorry about that
