### ISSUE TITLE
[WARN] [InteractionVisualizer] Task #2145001 for InteractionVisualizer v1.16.3.0 generated an exception

### ISSUE THREAD

**Issue by GentillePlume** [LOOHP/InteractionVisualizer#69]
Hello there.

I have multiple errors, this is one of many : 
server on 1.17.1

`[18:24:59]
[WARN] [InteractionVisualizer] Task #2145001 for InteractionVisualizer v1.16.3.0 generated an exception
java.lang.NoClassDefFoundError: ru/beykerykt/lightapi/LightType
at com.loohp.interactionvisualizer.managers.LightManager.deleteLight(LightManager.java:111) ~[?:?]
at com.loohp.interactionvisualizer.blocks.CraftingTableDisplay.process(CraftingTableDisplay.java:281) ~[?:?]
at com.loohp.interactionvisualizer.managers.TaskManager.lambda$run$0(TaskManager.java:418) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at com.loohp.interactionvisualizer.managers.TaskManager.lambda$run$1(TaskManager.java:418) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-107]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-107]
at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by LOOHP** [comment]
You are most likely not using the right LightAPI
https://github.com/Qveshn/LightAPI/releases/tag/3.5.2
