### ISSUE TITLE
[BUG] Interaction Visualizer LightAPI-Fork issues

### ISSUE THREAD

**Issue by fnrcum** [LOOHP/InteractionVisualizer#72]
Since we know the paper server now uses the starlight light engine, could we have IV  remove or ignore the lightapi-fork funactionalities until we have a proper solution? 

I know it would reduce the quality of the plugin a tad bit but this could be a stopgap for paper (and derivate) servers until we get a fix.

```ps1
[13:09:02 WARN]: [InteractionVisualizer] Task #981 for InteractionVisualizer v1.16.3.7 generated an exception
java.lang.NoClassDefFoundError: ru/beykerykt/lightapi/LightType
        at com.loohp.interactionvisualizer.managers.LightManager.lambda$run$0(LightManager.java:65) ~[InteractionVisualizer-1.16.3.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-356]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-356]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-356]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: ru.beykerykt.lightapi.LightType
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-356]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-356]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 9 more
```

**Comment by LOOHP** [comment]
The plugin can still work without LightAPI on 1.17+

**Comment by fnrcum** [comment]
It does, I just see a ton of errors. Should I just remove the LightApi-fork plugin alltogether?

**Comment by LOOHP** [comment]
Yea, you don't need it on 1.17+
