### ISSUE TITLE
An error occurred on the open 【CartographyTable/Loom】

### ISSUE THREAD

**Issue by SUNJIE-FOXMAIL** [LOOHP/InteractionVisualizer#75]
[13:08:12] [Server thread/INFO]: <LightAPI-Backward>: The package "ru.beykerykt.lightapi" is outdated! Switch to the new package "ru.beykerykt.minecraft.lightapi.*" or turn on the "force-enable-legacy" mode.
[13:08:12] [Server thread/WARN]: [InteractionVisualizer] Task #62 for InteractionVisualizer v1.17.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "c" is null
        at java.util.AbstractCollection.addAll(AbstractCollection.java:335) ~[?:?]
        at com.loohp.interactionvisualizer.managers.LightManager.lambda$run$0(LightManager.java:103) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>

[13:12:33] [Server thread/INFO]: <LightAPI-Backward>: The package "ru.beykerykt.lightapi" is outdated! Switch to the new package "ru.beykerykt.minecraft.lightapi.*" or turn on the "force-enable-legacy" mode.
[13:12:33] [Server thread/WARN]: [InteractionVisualizer] Task #62 for InteractionVisualizer v1.17.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "c" is null
        at java.util.AbstractCollection.addAll(AbstractCollection.java:335) ~[?:?]
        at com.loohp.interactionvisualizer.managers.LightManager.lambda$run$0(LightManager.java:103) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1205) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1033) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3336-Spigot-a5dea1c-a008701]
        at java.lang.Thread.run(Thread.java:833) [?:?]
>

**Comment by LOOHP** [comment]
LightAPI is no longer needed past Minecraft 1.17

**Comment by SUNJIE-FOXMAIL** [comment]
🆗
