### ISSUE TITLE
LightAPI error on 1.18

### ISSUE THREAD

**Issue by XionioXMaster** [LOOHP/InteractionVisualizer#77]
[18:56:05 WARN]: [InteractionVisualizer] Task #149 for InteractionVisualizer v1.17.0.8 generated an exception
java.lang.NoClassDefFoundError: ru/beykerykt/lightapi/LightType
        at com.loohp.interactionvisualizer.managers.LightManager.lambda$run$0(LightManager.java:65) ~[InteractionVisualizer-1.17.0.8.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1573) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1496) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[pufferfish-1.18.1.jar:git-Pufferfish-9]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: ru.beykerykt.lightapi.LightType
        ... 9 more

**Comment by LOOHP** [comment]
You do not need LightAPI on 1.18

**Comment by Futodama** [comment]
[10:00:15 WARN]: [InteractionVisualizer] Task #99 for InteractionVisualizer v1.17.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "ru.beykerykt.minecraft.lightapi.bukkit.internal.handler.IHandler.isLightingSupported(org.bukkit.World, int)" because "handler" is null
        at ru.beykerykt.lightapi.LightAPI.isSupported(LightAPI.java:357) ~[LightAPI-Bukkit-5.1.0.jar:?]
        at com.loohp.interactionvisualizer.managers.LightManager.lambda$run$0(LightManager.java:65) ~[InteractionVisualizer-1.17.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-100]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-100]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-100]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-100]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
