### ISSUE TITLE
Anvil Modification

### ISSUE THREAD

**Issue by 157946a** [LOOHP/InteractionVisualizer#86]
```
[19:55:51 WARN]: [InteractionVisualizer] Task #20099 for InteractionVisualizer v1.17.2.6 generated an exception
java.lang.NullPointerException: null
        at com.loohp.interactionvisualizer.libs.net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:242) ~[?:?]
        at com.loohp.interactionvisualizer.entityholders.Item.setCustomName(Item.java:74) ~[?:?]
        at com.loohp.interactionvisualizer.blocks.AnvilDisplay.process(AnvilDisplay.java:126) ~[?:?]
        at com.loohp.interactionvisualizer.managers.TaskManager.lambda$run$0(TaskManager.java:446) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_301]
        at com.loohp.interactionvisualizer.managers.TaskManager.lambda$run$1(TaskManager.java:446) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
```

This warning appears whenever an item name is modified with an anvil

**Comment by LOOHP** [comment]
Fixed in 1.17.2.7
