### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by Bloodlex** [LOOHP/InteractionVisualizer#90]
Server version: **Purpur version git-Purpur-1802 (MC: 1.19.2)**
InteractionVisualizer version: **InteractionVisualizer-1.18.1.0**

```
01.10 11:24:53 [Server] WARN Task #294 for InteractionVisualizer v1.18.1.0 generated an exception
01.10 11:24:53 [Server] INFO java.lang.NoSuchFieldError: P
01.10 11:24:53 [Server] INFO at com.loohp.interactionvisualizer.nms.V1_19.getEntities(V1_19.java:205) ~[InteractionVisualizer-1.18.1.0.jar:?]
01.10 11:24:53 [Server] INFO at com.loohp.interactionvisualizer.entities.ItemDisplay$1.run(ItemDisplay.java:161) ~[InteractionVisualizer-1.18.1.0.jar:?]
01.10 11:24:53 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1802]
01.10 11:24:53 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LOOHP** [comment]
You need to update to the latest dev build.

**Comment by Bloodlex** [comment]
> You need to update to the latest dev build.

Thanks, I'll try 🙂
