### ISSUE TITLE
Reoccuring error on 1.19.2 Purpur 1824

### ISSUE THREAD

**Issue by Wolvend** [LOOHP/InteractionVisualizer#91]
[17:43:51 WARN]: [InteractionVisualizer] Task #218 for InteractionVisualizer v1.18.1.0 generated an exception
java.lang.NoSuchFieldError: P
        at com.loohp.interactionvisualizer.nms.V1_19.getEntities(V1_19.java:205) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay$1.run(ItemDisplay.java:161) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:52 WARN]: [InteractionVisualizer] Task #218 for InteractionVisualizer v1.18.1.0 generated an exception
java.lang.NoSuchFieldError: P
        at com.loohp.interactionvisualizer.nms.V1_19.getEntities(V1_19.java:205) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay$1.run(ItemDisplay.java:161) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:43:53 WARN]: [InteractionVisualizer] Task #218 for InteractionVisualizer v1.18.1.0 generated an exception
java.lang.NoSuchFieldError: P
        at com.loohp.interactionvisualizer.nms.V1_19.getEntities(V1_19.java:205) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at com.loohp.interactionvisualizer.entities.ItemDisplay$1.run(ItemDisplay.java:161) ~[InteractionVisualizer-1.18.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1824]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LOOHP** [comment]
#90
